// fetch the files that xegos exist in
import { promises as fs } from "fs";
import fileEndings from "./file-endings";

/*
This code is reading a text file and parsing the contents into xego commands.
- generated by stenography 🤖
*/
const readXegoTxtFile = async (path: string) => {
    if (!path.endsWith(".txt")) {
        throw new Error("Path must end with .txt");
    }
    const xegoFile = await fs.readFile(path, "utf8");
    let xegoCommand = ''
    let fileEnding = ''
    let xegos = xegoFile.split("\n")
    for (let i = 0; i < xegos.length; i++) {
        if (i === 0) {
            fileEnding = fileEndings[xegos[i].split(":")[1].trim()]
        } else {
            const ll = await fs.readFile('xegos/' + xegos[i] + fileEnding, "utf8");
            xegoCommand += ll + "\n"
        }
    }
    // await fs.writeFile(path + 'xego-tower' + fileEnding, xegoCommand);
    return xegoCommand
}

export {
    readXegoTxtFile
}